### ISSUE TITLE
:gift: m3 validator

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/amigos#29]
A lot of what needs to be done here can be determined by 
- https://github.com/notch8/hykuup_knapsack/issues/378

Validation rules

- [x] - validate schema (houndstooth validator)
- [x] - required properties exist
  - [x] available_on/class
  - [x] range
  - [x] display_label/default 
- [ ] - check for existences of local vocab if one is being referred (will do after controlled vocab pr gets merged) 
  - [ ] https://github.com/samvera/hyku/pull/2608
- [x] - check that the backend supports all the models listed in available_on.classes
- [x] - title cardinality - if no maximum caused issues
- [x] label for FileSet class to allow filesets to work
- [ ] ~form + any one sub key to not break the form (required, primary, multi_value... I think you can also put display: false to not show it on the form) per [LaRita](https://github.com/samvera/hyku/pull/2617#issuecomment-3081388111)~ NOT NEEDED
- [x] core metadata 
- [x]   - prevent app from crashing when there's bad data

# Testing Instructions

See [comment](https://github.com/notch8/amigos/issues/29#issuecomment-3109696483)

# Acceptance Criteria 
- [ ] validations are included in the m3 uploader process to prevent users from saving bad profiles and crashing the app

## NOTES

- https://github.com/samvera-labs/houndstooth/blob/main/validate.rb (Houndstooth)
- https://github.com/utkdigitalinitiatives/m3_profiles/blob/main/utilities/validate.py (UTK validator for allinson flex)

**Comment by ShanaLMoore** [comment]
this appears to be an environmental thing. I can't reproduce this locally however I switched to another (not st jude tenant) and it's also occurring there too. I tried redeploying friends.

**Comment by ShanaLMoore** [comment]
Should indexing include what we currently use index_documentation for? 

In the existing m3 profile schema, indexing includes values like [displayable, searchable, etc...]. Our current schema is invalid because we use the indexing_keys like *_tesim, etc. 

Does it make sense to [change the m3 profile schema](https://github.com/samvera-labs/houndstooth/pull/34/files)? Or, does it make more sense to change flexible metadata so that it can continue accepting either indexing_keys or index_documentation values? Who else uses houndstooth? 

Allinson flex use to accept and transform them before saving: https://github.com/samvera-labs/allinson_flex/blob/2516ad1b84ee02b87c34118b729095e2a6e83ee2/app/services/allinson_flex/dynamic_schema_service.rb#L196-L229

To achieve the same we would need to add a similar method [here](https://github.com/samvera/hyrax/blob/5.0-flexible/app/models/hyrax/flexible_schema.rb#L109) to transform the values. 

backwards compatibility?

Additionally m3 profile schema has cardinality and no multi_value. Why do we have both?

**Comment by ShanaLMoore** [comment]
### **QA Guide for Metadata Profile Validation**

This guide provides detailed test cases for validating a metadata profile YAML file. The goal is to ensure that the profile conforms to all the application's rules before it's loaded. You will be testing by editing a [metadata profile file ](https://github.com/samvera/hyku/blob/main/config/metadata_profiles/m3_profile.yaml)and observing the validation errors.

⚠️ **Please take liberty with your own tests too. We want to add a validation rule to any scenario that would cause the user to crash their app because they uploaded a "bad" or invalid profile.** 

### **Test Cases: Core Metadata Validation**

**Objective:** To ensure all core metadata properties are defined and correctly configured in the profile.

#### **Test Case 1.1: Verify Presence of All Core Properties**

1.  **Setup:** Open your metadata profile YAML file.
2.  **Action:** In the `properties` section of the file, delete the entire block for one of the core properties, for example, `depositor`.
3.  **Expected Result:** The validation should fail with an error message: `Missing required property: depositor.`
4.  **Cleanup:** Restore the property you deleted. Repeat for other core properties to ensure the check is comprehensive.

#### **Test Case 1.2: Verify `data_type` for Multi-Value Properties**
Some core properties can have multiple values (`title`, `description`, `keyword`, `creator`, `license`), while others can only have one. This is controlled by the `data_type`.
1.  **Setup:** In the profile, locate the `title` property, which should be multi-value.
2.  **Action:** Change its `data_type` from `array` to `string`.
3.  **Expected Result:** The validation should fail with an error: `Property 'title' must have data_type set to 'array'.`
4.  **Cleanup:** Revert the `data_type` to `array`.

#### **Test Case 1.3: Verify Required Indexing Keys**
Core properties must be indexed for searching in specific ways.
1.  **Setup:** In the profile, locate the `depositor` property. It should have an `indexing` list.
2.  **Action:** The `depositor` property is required to have `depositor_ssim`. Remove just that key from its `indexing` list.
3.  **Expected Result:** The validation should fail with an error: `Property 'depositor' is missing required indexing: depositor_ssim.`
4.  **Cleanup:** Restore the `depositor_ssim` key.

#### **Test Case 1.4: Verify RDF Predicate (`property_uri`)**
Each core property maps to a standard RDF predicate.
1.  **Setup:** In the profile, locate the `title` property.
2.  **Action:** Change its `property_uri` to an incorrect value, like `http://example.com/wrong-predicate`. The correct value is `http://purl.org/dc/terms/title`.
3.  **Expected Result:** The validation should fail with an error: `Property 'title' must have property_uri set to http://purl.org/dc/terms/title.`
4.  **Cleanup:** Restore the correct `property_uri`.

#### **Test Case 1.5: Verify Availability on All Classes**
Core properties must be available for all work types defined in the profile.
1.  **Setup:**
    *   In the `classes` section of your profile, identify all the work types listed (e.g., `GenericWork`, `Book`).
    *   Locate a core property, like `creator`.
2.  **Action:** From the `creator` property's `available_on.class` list, remove one of the work types you identified (e.g., remove `GenericWork`).
3.  **Expected Result:** The validation should fail with an error: `Property 'creator' must be available on all classes, but is missing from: GenericWork.`
4.  **Cleanup:** Add the work type back to the `available_on.class` list.

#### **Test Case 1.6: Verify `title` Cardinality**
The `title` property must always be required.
1.  **Setup:** In the profile, locate the `title` property.
2.  **Action:** Under its `cardinality` section, change the `minimum` value to `0`.
3.  **Expected Result:** The validation should fail with an error: `Property 'title' must have a cardinality minimum of at least 1.`
4.  **Cleanup:** Change the `minimum` value back to `1`.


#### *Test Case 1.7: Verify creator Multi-Value (data_type)*

The creator property must always be multi-valued (i.e., `data_type: array`).

1.  **Setup**  
  – In the profile, locate the `creator` property.  
2. **Action  1**
  – In that property’s configuration, change `data_type` from `array` to `string`.  
3. **Action  2**
  – Remove the property entirely
4. ** Expected Result**  
  – Run the validator.  
  – Validation should fail with the error:  1.  Property 'creator' must have data_type set to 'array'; 2. missing property error
5. **Cleanup** 1. Revert `data_type` back to `array`; 2. Replace creator property

---

### **Test Cases: General Schema and Class Validation**

**Objective:** To ensure the profile structure is sound and uses valid, registered classes.

#### **Test Case 2.1: Verify Presence of Required Base Classes**
1.  **Setup:** Open your metadata profile YAML file.
2.  **Action:** In the `classes` section, delete the `Hyrax::FileSet` class definition.
3.  **Expected Result:** The validation should fail with an error: `Missing required classes: Hyrax::FileSet.`
4.  **Cleanup:** Restore the `Hyrax::FileSet` class. Repeat for `Hyrax::AdminSet` and `Hyrax::Collection`.

#### **Test Case 2.2: Verify Registered Class Names**
The profile cannot use work types that don't actually exist in the application.
1.  **Setup:** Open your metadata profile YAML file.
2.  **Action:** In the `properties` section, for any property, add a non-existent class name like `"InvalidWorkType"` to its `available_on.class` list.
3.  **Expected Result:** The validation should fail with an error listing the invalid class: `Invalid classes: InvalidWorkType.`
4.  **Cleanup:** Remove the invalid class name.

#### **Test Case 2.3: Verify `label` Property Configuration**
A special `label` property is required for file sets.
1.  **Setup:** Locate the `label` property in the profile.
2.  **Action (Test A):** Remove `Hyrax::FileSet` from the `label` property's `available_on.class` list.
3.  **Expected Result (Test A):** The validation should fail with an error: `Label must be available on Hyrax::FileSet.`
4.  **Action (Test B):** Restore `Hyrax::FileSet`, then delete the entire `label` property from the profile.
5.  **Expected Result (Test B):** The validation should fail with a different error: `A \`label\` property is required.`
6.  **Cleanup:** Restore the `label` property.

Of course. Here is a test case for `validate_enabled_work_types` that follows the format you provided.

***

### Test Case 2.4: Verify Synchronization of Enabled and Profiled Work Types

This test ensures that the list of work types enabled for the current tenant matches exactly with the work types defined in the metadata profile, checking for mismatches in both directions.

*   **Setup:**
    *   Ensure the application has `GenericWork`, `Image`, and `Etd` registered as official work types (`curation_concern_types`).
    *   Configure the current tenant's `Site` instance to have its `available_works` set to `['GenericWork', 'Image']`.
    *   Load a flexible metadata profile that contains definitions for `GenericWorkResource`, `ImageResource`, and `EtdResource`.

*   **Action (Test A):** Remove the `ImageResource` class definition from the loaded profile. This creates a scenario where a work type is enabled for the tenant but is not defined in the profile.
*   **Expected Result (Test A):** The validation fails with the error: `Enabled work types not in profile: Image.`

*   **Action (Test B):** Restore the `ImageResource` class to the profile. Then, update the `Site` instance by setting its `available_works` to only `['GenericWork']`. This creates the inverse scenario where the profile defines work types (`ImageResource`, `EtdResource`) that are not enabled for the tenant.
*   **Expected Result (Test B):** The validation fails with the error: `Profile includes work types that are not enabled: Image, EtD.`

*   **Cleanup:** Restore the profile and the `Site` instance to their original states from the setup step.

**Comment by ShanaLMoore** [comment]
branch deployed to hykustaging.org ✅

**Comment by sjproctor** [comment]
If a Work Type (not collection) is **not** listed in the `classes` section and is listed in the `available_on` section, this will cause the app to break. 

In this example, I removed the `GenericWorkResource` from the classes attributes but did not remove it from the properties `available_on` which caused the application to break.

<img width="1605" height="843" alt="Image" src="https://github.com/user-attachments/assets/296e51fa-14f9-491e-9d96-643435d7d214" />

**Comment by sjproctor** [comment]
Removing the creator attribute will still allow a profile to be uploaded successfully. However, creating a work will fail.

<img width="1564" height="849" alt="Image" src="https://github.com/user-attachments/assets/76b5bdcd-93bf-47fa-9f28-26a9f8a43c54" />

**Comment by sjproctor** [comment]
A profile with no work types can be successfully created but will fail when attempting to create a work.

<img width="1544" height="780" alt="Image" src="https://github.com/user-attachments/assets/c266d640-4571-4537-b3fc-b24691058f84" />

**Comment by sjproctor** [comment]
These are notes from the full test of the required-only metadata profile. Issues are noted in the previous comments.


```yml
---
m3_version: 1.0.beta2 # Removing this is caught by the validator (Schema error at ``: Missing required properties: 'm3_version'.)
profile: # Removing this is caught by the validator (Schema error at ``: Missing required properties: 'profile'.)
  date_modified: '2025-07-22' # Removing this is caught by the validator (Schema error at `/profile`: Missing required properties: 'date_modified'.)
  responsibility: https://test.com # Removing this is caught by the validator (Schema error at `/profile`: Missing required properties: 'responsibility'.)
classes: # Removing this is caught by the validator (undefined method `keys' for nil:NilClass)
  AdminSetResource:
    display_label: Admin Set # Removing this is caught by the validator (Missing required classes: AdminSetResource.)
  CollectionResource:
    display_label: PCDM Collection # Removing this is caught by the validator (Missing required classes: CollectionResource.)
  Hyrax::FileSet:
    display_label: File Set # Removing this is caught by the validator (Missing required classes: Hyrax::FileSet.)
  GenericWorkResource: # !! BREAK APP: Removing this without removing the work type from available_on will break the app
    display_label: Generic Work # !! BREAK WORK: Removing all references (classes and all properties) to a work type (not a collection) will allow you to make a profile but will break when submitting a work
properties:
  title: # Removing this is caught by the validator (Removing this is caught by the validator)
    available_on: # Removing this is caught by the validator (Schema error at `/properties/title`: Missing required properties: 'available_on'., Property 'title' must be available on all classes, but is missing from: AdminSetResource, CollectionResource, Hyrax::FileSet, GenericWorkResource.)
      class:
      - AdminSetResource
      - Hyrax::FileSet
      - CollectionResource
      - GenericWorkResource
    multi_value: true # Removing this is caught by the validator (Property 'title' must have multi_value set to true.)
    display_label:
      default: Title # Removing this is caught by the validator (Schema error at `/properties/title`: Missing required properties: 'display_label'.)
    indexing: # Removing this is caught by the validator (Property 'title' is missing required indexing: title_sim, title_tesim.)
    - title_sim
    - title_tesim
    form:
      required: true # Removing this means it doesn't show up on the form, a work can be created but there is no way to add a title
      primary: true # Removing this means it is only visible after selecting "Additional fields"
    property_uri: http://purl.org/dc/terms/title # Removing this is caught by the validator (Property 'title' must have property_uri set to http://purl.org/dc/terms/title.)
    range: http://www.w3.org/2001/XMLSchema#string # Removing this is caught by the validator (Schema error at `/properties/title`: Missing required properties: 'range'.)
  date_modified: # Removing this is caught by the validator (Missing required property: date_modified.)
    available_on:
      class:
      - AdminSetResource
      - Hyrax::FileSet
      - CollectionResource
      - GenericWorkResource
    display_label:
      default: Date Modified
    range: http://www.w3.org/2001/XMLSchema#dateTime
    property_uri: http://purl.org/dc/terms/modified
  date_uploaded:  # Removing this is caught by the validator (Missing required property: date_uploaded.)
    available_on:
      class:
      - AdminSetResource
      - Hyrax::FileSet
      - CollectionResource
      - GenericWorkResource
    display_label:
      default: Date Uploaded
    range: http://www.w3.org/2001/XMLSchema#dateTime
    property_uri: http://purl.org/dc/terms/dateSubmitted
  depositor: # Removing this is caught by the validator (Missing required property: depositor.)
    available_on:
      class:
      - AdminSetResource
      - Hyrax::FileSet
      - CollectionResource
      - GenericWorkResource
    display_label:
      default: Depositor
    indexing:
      - depositor_ssim
      - depositor_tesim
    range: http://www.w3.org/2001/XMLSchema#string
    property_uri: http://id.loc.gov/vocabulary/relators/dpt
  creator: # !!BREAK WORK: Removing creator will allow you to make a profile but will break when submitting a work
    available_on:
      class:
      - AdminSetResource
      - Hyrax::FileSet
      - CollectionResource
      - GenericWorkResource
    display_label:
      default: Creator
    range: http://www.w3.org/2001/XMLSchema#string
  label: # Removing this is caught by the validator (A `label` property is required.)
    available_on: # Removing this is caught by the validator (Schema error at `/properties/label`: Missing required properties: 'available_on'., Label must be available on Hyrax::FileSet.)
      class:
      - Hyrax::FileSet
    display_label:
      default: Label
    range: http://www.w3.org/2001/XMLSchema#string
```
